create table if not exists public.reservas_eventos (
  id bigint generated by default as identity primary key,
  fecha_evento date not null,
  cliente_nombre text not null,
  cliente_telefono text,
  tipo_evento text not null,
  anticipo text,
  notas text,
  estado text not null default 'reservado' check (estado in ('reservado', 'finalizado', 'cancelado')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

DROP TRIGGER IF EXISTS trg_reservas_eventos_updated_at ON public.reservas_eventos;
create trigger trg_reservas_eventos_updated_at
before update on public.reservas_eventos
for each row
execute function public.set_updated_at();

create index if not exists reservas_eventos_fecha_idx on public.reservas_eventos (fecha_evento);
create index if not exists reservas_eventos_estado_idx on public.reservas_eventos (estado);
create index if not exists reservas_eventos_cliente_idx on public.reservas_eventos (cliente_nombre);

-- Evita fechas duplicadas SOLO cuando la fecha está activa.
-- Si la reserva se cancela, esa fecha vuelve a poder usarse.
create unique index if not exists reservas_eventos_fecha_activa_uidx
on public.reservas_eventos (fecha_evento)
where estado in ('reservado', 'finalizado');

alter table public.reservas_eventos enable row level security;

-- Sin login: cualquier visitante con el link puede consultar y gestionar.
-- Es cómodo para una agenda simple, pero para producción real conviene protegerlo.
DROP POLICY IF EXISTS "lectura_publica_reservas" ON public.reservas_eventos;
create policy "lectura_publica_reservas"
on public.reservas_eventos
for select
to anon, authenticated
using (true);

DROP POLICY IF EXISTS "insertar_publico_reservas" ON public.reservas_eventos;
create policy "insertar_publico_reservas"
on public.reservas_eventos
for insert
to anon, authenticated
with check (true);

DROP POLICY IF EXISTS "actualizar_publico_reservas" ON public.reservas_eventos;
create policy "actualizar_publico_reservas"
on public.reservas_eventos
for update
to anon, authenticated
using (true)
with check (true);

comment on table public.reservas_eventos is 'Agenda de reservas para eventos. Las canceladas liberan la fecha.';
